### ISSUE TITLE
Code and docs?

### ISSUE THREAD

**Issue by zvezdochiot** [plzombie/djvupure#1]
Hi @plzombie .

Small request: Keep this repository clean, code only. Move all examples and heavy documentation to separate repositories: `djvupure-doc` and `djvupure-examples`. In the documentation of this repository, add only links to these 2.

**Comment by plzombie** [comment]
And what do you propose? Create separate repositories djvupure-lib, djvupure-tools, djvupure-docs and link them to djvupure repository as submodules?

**Comment by zvezdochiot** [comment]
Hi @plzombie .

Not. Only `djvupure-doc` and `djvupure-examples`.

**Comment by plzombie** [comment]
Ok. Not planned to move demos to main repository anyway
